//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Scada.Client.SL.SystemManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemManagerService.SystemManagerServiceSoap")]
    public interface SystemManagerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddDD", ReplyAction="*")]
        System.IAsyncResult BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndAddDD(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ListStudents", ReplyAction="*")]
        System.IAsyncResult BeginListStudents(Scada.Client.SL.SystemManagerService.ListStudentsRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.ListStudentsResponse EndListStudents(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListStudents", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.ListStudentsRequestBody Body;
        
        public ListStudentsRequest() {
        }
        
        public ListStudentsRequest(Scada.Client.SL.SystemManagerService.ListStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListStudentsRequestBody {
        
        public ListStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.ListStudentsResponseBody Body;
        
        public ListStudentsResponse() {
        }
        
        public ListStudentsResponse(Scada.Client.SL.SystemManagerService.ListStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListStudentsResult;
        
        public ListStudentsResponseBody() {
        }
        
        public ListStudentsResponseBody(string ListStudentsResult) {
            this.ListStudentsResult = ListStudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemManagerServiceSoapChannel : Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddDDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddDDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemManagerServiceSoapClient : System.ServiceModel.ClientBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap>, Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap {
        
        private BeginOperationDelegate onBeginAddDDDelegate;
        
        private EndOperationDelegate onEndAddDDDelegate;
        
        private System.Threading.SendOrPostCallback onAddDDCompletedDelegate;
        
        private BeginOperationDelegate onBeginListStudentsDelegate;
        
        private EndOperationDelegate onEndListStudentsDelegate;
        
        private System.Threading.SendOrPostCallback onListStudentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SystemManagerServiceSoapClient() {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AddDDCompletedEventArgs> AddDDCompleted;
        
        public event System.EventHandler<ListStudentsCompletedEventArgs> ListStudentsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddDD(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndAddDD(System.IAsyncResult result) {
            return base.Channel.EndAddDD(result);
        }
        
        private System.IAsyncResult OnBeginAddDD(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginAddDD(x, y, callback, asyncState);
        }
        
        private object[] OnEndAddDD(System.IAsyncResult result) {
            int retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndAddDD(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddDDCompleted(object state) {
            if ((this.AddDDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddDDCompleted(this, new AddDDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddDDAsync(int x, int y) {
            this.AddDDAsync(x, y, null);
        }
        
        public void AddDDAsync(int x, int y, object userState) {
            if ((this.onBeginAddDDDelegate == null)) {
                this.onBeginAddDDDelegate = new BeginOperationDelegate(this.OnBeginAddDD);
            }
            if ((this.onEndAddDDDelegate == null)) {
                this.onEndAddDDDelegate = new EndOperationDelegate(this.OnEndAddDD);
            }
            if ((this.onAddDDCompletedDelegate == null)) {
                this.onAddDDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddDDCompleted);
            }
            base.InvokeAsync(this.onBeginAddDDDelegate, new object[] {
                        x,
                        y}, this.onEndAddDDDelegate, this.onAddDDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginListStudents(Scada.Client.SL.SystemManagerService.ListStudentsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListStudents(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginListStudents(System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.ListStudentsRequest inValue = new Scada.Client.SL.SystemManagerService.ListStudentsRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.ListStudentsRequestBody();
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginListStudents(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.ListStudentsResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndListStudents(System.IAsyncResult result) {
            return base.Channel.EndListStudents(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndListStudents(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.ListStudentsResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndListStudents(result);
            return retVal.Body.ListStudentsResult;
        }
        
        private System.IAsyncResult OnBeginListStudents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginListStudents(callback, asyncState);
        }
        
        private object[] OnEndListStudents(System.IAsyncResult result) {
            string retVal = this.EndListStudents(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListStudentsCompleted(object state) {
            if ((this.ListStudentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListStudentsCompleted(this, new ListStudentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListStudentsAsync() {
            this.ListStudentsAsync(null);
        }
        
        public void ListStudentsAsync(object userState) {
            if ((this.onBeginListStudentsDelegate == null)) {
                this.onBeginListStudentsDelegate = new BeginOperationDelegate(this.OnBeginListStudents);
            }
            if ((this.onEndListStudentsDelegate == null)) {
                this.onEndListStudentsDelegate = new EndOperationDelegate(this.OnEndListStudents);
            }
            if ((this.onListStudentsCompletedDelegate == null)) {
                this.onListStudentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListStudentsCompleted);
            }
            base.InvokeAsync(this.onBeginListStudentsDelegate, null, this.onEndListStudentsDelegate, this.onListStudentsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap CreateChannel() {
            return new SystemManagerServiceSoapClientChannel(this);
        }
        
        private class SystemManagerServiceSoapClientChannel : ChannelBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap>, Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap {
            
            public SystemManagerServiceSoapClientChannel(System.ServiceModel.ClientBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = x;
                _args[1] = y;
                System.IAsyncResult _result = base.BeginInvoke("AddDD", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddDD(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddDD", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListStudents(Scada.Client.SL.SystemManagerService.ListStudentsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ListStudents", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.ListStudentsResponse EndListStudents(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.ListStudentsResponse _result = ((Scada.Client.SL.SystemManagerService.ListStudentsResponse)(base.EndInvoke("ListStudents", _args, result)));
                return _result;
            }
        }
    }
}
