<?xml version="1.0" encoding="utf-8"?><Database Name="SCADA" Class="SCADADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=YANGHONGKANG;Initial Catalog=SCADA;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="SCADAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatabaseBackUp" Member="DatabaseBackUps">
    <Type Name="DatabaseBackUp">
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DatabaseName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BackUpDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BackUpSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BackUpPeople" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Department_User" Member="Users" ThisKey="ID" OtherKey="DeptID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceAlarm" Member="DeviceAlarms">
    <Type Name="DeviceAlarm">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeviceNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EventType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DealStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DealPeople" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="DeviceInfo_DeviceAlarm" Member="DeviceInfo" ThisKey="DeviceID" OtherKey="ID" Type="DeviceInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceInfo" Member="DeviceInfos">
    <Type Name="DeviceInfo">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HardType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeviceMAC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SIMNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ManageAreaID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="InstallPlace" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Dimensionality" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ConnectPoint" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Coordinate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ConnectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainDNS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SecondDNS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CenterIP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Domain" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CollectFreq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlarmTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AlarmDown" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Windage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TimeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCDScreenDisplayType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UseUrgencyButton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process1Enable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process1HigherValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process1HighValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process1LowValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process1LowerValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process1RateValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process2Enable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process2HigherValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process2HighValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process2LowValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process2LowerValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process2RateValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process3Enable" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process3HigherValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process3HighValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process3LowValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process3LowerValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process3RateValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process4Enable" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process4HigherValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process4HighValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process4LowValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process4LowerValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process4RateValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5Enable" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5HigherValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5HighValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process5LowValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5LowerValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5RateValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DeviceInfo_DeviceAlarm" Member="DeviceAlarms" ThisKey="ID" OtherKey="DeviceID" Type="DeviceAlarm" />
      <Association Name="DeviceInfo_DeviceLog" Member="DeviceLogs" ThisKey="ID" OtherKey="DeviceID" Type="DeviceLog" />
      <Association Name="DeviceInfo_DeviceMaintenancePeople" Member="DeviceMaintenancePeoples" ThisKey="ID" OtherKey="DeviceID" Type="DeviceMaintenancePeople" />
      <Association Name="DeviceInfo_DeviceRealTime" Member="DeviceRealTimes" ThisKey="ID" OtherKey="DeviceID" Type="DeviceRealTime" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceLog" Member="DeviceLogs">
    <Type Name="DeviceLog">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeviceNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LogPeople" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LogTIme" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DeviceInfo_DeviceLog" Member="DeviceInfo" ThisKey="DeviceID" OtherKey="ID" Type="DeviceInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceMaintenancePeople" Member="DeviceMaintenancePeoples">
    <Type Name="DeviceMaintenancePeople">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaintenanceID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeviceID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="DeviceInfo_DeviceMaintenancePeople" Member="DeviceInfo" ThisKey="DeviceID" OtherKey="ID" Type="DeviceInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceRealTime" Member="DeviceRealTimes">
    <Type Name="DeviceRealTime">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DeviceNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Temperature" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Electricity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Signal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process4Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Process5Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DeviceInfo_DeviceRealTime" Member="DeviceInfo" ThisKey="DeviceID" OtherKey="ID" Type="DeviceInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceTree" Member="DeviceTrees">
    <Type Name="DeviceTree">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AdminID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="User_DeviceTree" Member="User" ThisKey="AdminID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MaintenancePeople" Member="MaintenancePeoples">
    <Type Name="MaintenancePeople">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MainNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MainName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Native" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MobileBack" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Column_9" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module">
      <Column Name="ModuleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ModuleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Module_RoleModule" Member="RoleModules" ThisKey="ModuleID" OtherKey="ModuleID" Type="RoleModule" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" />
      <Association Name="Role_RoleModule" Member="RoleModules" ThisKey="RoleID" OtherKey="RoleID" Type="RoleModule" />
    </Type>
  </Table>
  <Table Name="dbo.RoleModule" Member="RoleModules">
    <Type Name="RoleModule">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Module_RoleModule" Member="Module" ThisKey="ModuleID" OtherKey="ModuleID" Type="Module" IsForeignKey="true" />
      <Association Name="Role_RoleModule" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DeptID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="UserID" OtherKey="UserID" Type="UserRole" />
      <Association Name="User_DeviceTree" Member="DeviceTrees" ThisKey="UserID" OtherKey="AdminID" Type="DeviceTree" />
      <Association Name="Department_User" Member="Department" ThisKey="DeptID" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>