//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ListSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ListSampleDataSource { }
#else

	public class ListSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ListSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/BJOCRM;component/SampleData/ListSampleDataSource/ListSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _name = string.Empty;

		public string name
		{
			get
			{
				return this._name;
			}

			set
			{
				if (this._name != value)
				{
					this._name = value;
					this.OnPropertyChanged("name");
				}
			}
		}

		private string _dwp = string.Empty;

		public string dwp
		{
			get
			{
				return this._dwp;
			}

			set
			{
				if (this._dwp != value)
				{
					this._dwp = value;
					this.OnPropertyChanged("dwp");
				}
			}
		}

		private bool _je = false;

		public bool je
		{
			get
			{
				return this._je;
			}

			set
			{
				if (this._je != value)
				{
					this._je = value;
					this.OnPropertyChanged("je");
				}
			}
		}

		private string _quyue = string.Empty;

		public string quyue
		{
			get
			{
				return this._quyue;
			}

			set
			{
				if (this._quyue != value)
				{
					this._quyue = value;
					this.OnPropertyChanged("quyue");
				}
			}
		}

		private string _yuefen = string.Empty;

		public string yuefen
		{
			get
			{
				return this._yuefen;
			}

			set
			{
				if (this._yuefen != value)
				{
					this._yuefen = value;
					this.OnPropertyChanged("yuefen");
				}
			}
		}

		private System.Windows.Media.ImageSource _qushi = null;

		public System.Windows.Media.ImageSource qushi
		{
			get
			{
				return this._qushi;
			}

			set
			{
				if (this._qushi != value)
				{
					this._qushi = value;
					this.OnPropertyChanged("qushi");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
