//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessRules.RealTimeDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RealTimeDataService.IRealTimeService")]
    public interface IRealTimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeService/UserEventDataReceive", ReplyAction="http://tempuri.org/IRealTimeService/UserEventDataReceiveResponse")]
        void UserEventDataReceive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeService/AlarmDataReceived", ReplyAction="http://tempuri.org/IRealTimeService/AlarmDataReceivedResponse")]
        void AlarmDataReceived();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeService/ReaTimeDataReceivedReceive", ReplyAction="http://tempuri.org/IRealTimeService/ReaTimeDataReceivedReceiveResponse")]
        void ReaTimeDataReceivedReceive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeServiceChannel : BusinessRules.RealTimeDataService.IRealTimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeServiceClient : System.ServiceModel.ClientBase<BusinessRules.RealTimeDataService.IRealTimeService>, BusinessRules.RealTimeDataService.IRealTimeService {
        
        public RealTimeServiceClient() {
        }
        
        public RealTimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UserEventDataReceive() {
            base.Channel.UserEventDataReceive();
        }
        
        public void AlarmDataReceived() {
            base.Channel.AlarmDataReceived();
        }
        
        public void ReaTimeDataReceivedReceive() {
            base.Channel.ReaTimeDataReceivedReceive();
        }
    }
}
