//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Scada.Framework.RIA
{
    #region 上下文

    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Scada : ObjectContext
    {
        #region 构造函数

        /// <summary>
        /// 请使用应用程序配置文件的“ScadaCon”部分中的连接字符串初始化新 ScadaCon 对象。
        /// </summary>
        public Scada()
            : base(DefaultConfiguration.Default_ConnectionString)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 ScadaCon 对象。
        /// </summary>
        public Scada(EntityConnection connection)
            : base(connection, DefaultConfiguration.Default_ConnectionString)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region 分部方法

        partial void OnContextCreated();

        #endregion

        #region ObjectSet 属性

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_User> Sys_User
        {
            get
            {
                if ((_Sys_User == null))
                {
                    _Sys_User = base.CreateObjectSet<Sys_User>("Sys_User");
                }
                return _Sys_User;
            }
        }
        private ObjectSet<Sys_User> _Sys_User;

        #endregion

        #region AddTo 方法

        /// <summary>
        /// 用于向 Sys_User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_User(Sys_User sys_User)
        {
            base.AddObject("Sys_User", sys_User);
        }

        #endregion

    }


    #endregion

    #region 实体

    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ScadaModel", Name = "Sys_User")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Sys_User : EntityObject
    {
        #region 工厂方法

        /// <summary>
        /// 创建新的 Sys_User 对象。
        /// </summary>
        /// <param name="user_ID">User_ID 属性的初始值。</param>
        public static Sys_User CreateSys_User(global::System.Int32 user_ID)
        {
            Sys_User sys_User = new Sys_User();
            sys_User.User_ID = user_ID;
            return sys_User;
        }

        #endregion
        #region 基元属性

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_ID
        {
            get
            {
                return _User_ID;
            }
            set
            {
                if (_User_ID != value)
                {
                    OnUser_IDChanging(value);
                    ReportPropertyChanging("User_ID");
                    _User_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("User_ID");
                    OnUser_IDChanged();
                }
            }
        }
        private global::System.Int32 _User_ID;
        partial void OnUser_IDChanging(global::System.Int32 value);
        partial void OnUser_IDChanged();

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String User_Name
        {
            get
            {
                return _User_Name;
            }
            set
            {
                OnUser_NameChanging(value);
                ReportPropertyChanging("User_Name");
                _User_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_Name");
                OnUser_NameChanged();
            }
        }
        private global::System.String _User_Name;
        partial void OnUser_NameChanging(global::System.String value);
        partial void OnUser_NameChanged();

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String User_PassWord
        {
            get
            {
                return _User_PassWord;
            }
            set
            {
                OnUser_PassWordChanging(value);
                ReportPropertyChanging("User_PassWord");
                _User_PassWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_PassWord");
                OnUser_PassWordChanged();
            }
        }
        private global::System.String _User_PassWord;
        partial void OnUser_PassWordChanging(global::System.String value);
        partial void OnUser_PassWordChanged();

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String User_Email
        {
            get
            {
                return _User_Email;
            }
            set
            {
                OnUser_EmailChanging(value);
                ReportPropertyChanging("User_Email");
                _User_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_Email");
                OnUser_EmailChanged();
            }
        }
        private global::System.String _User_Email;
        partial void OnUser_EmailChanging(global::System.String value);
        partial void OnUser_EmailChanged();

        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String User_Status
        {
            get
            {
                return _User_Status;
            }
            set
            {
                OnUser_StatusChanging(value);
                ReportPropertyChanging("User_Status");
                _User_Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_Status");
                OnUser_StatusChanged();
            }
        }
        private global::System.String _User_Status;
        partial void OnUser_StatusChanging(global::System.String value);
        partial void OnUser_StatusChanged();

        #endregion

    }

    #endregion

}
