//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Scada.Client.SL.SystemManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemManagerService.SystemManagerServiceSoap")]
    public interface SystemManagerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddDD", ReplyAction="*")]
        System.IAsyncResult BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndAddDD(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLoginResultType", ReplyAction="*")]
        System.IAsyncResult BeginGetLoginResultType(Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse EndGetLoginResultType(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        System.IAsyncResult BeginGetWeather(Scada.Client.SL.SystemManagerService.GetWeatherRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.GetWeatherResponse EndGetWeather(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetSystemParameterManage", ReplyAction="*")]
        System.IAsyncResult BeginGetSystemParameterManage(Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse EndGetSystemParameterManage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetSystemGlobalParameter", ReplyAction="*")]
        System.IAsyncResult BeginGetSystemGlobalParameter(Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse EndGetSystemGlobalParameter(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateSystemParameterManage", ReplyAction="*")]
        System.IAsyncResult BeginUpdateSystemParameterManage(Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse EndUpdateSystemParameterManage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateSystemGlobalParameter", ReplyAction="*")]
        System.IAsyncResult BeginUpdateSystemGlobalParameter(Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState);
        
        Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse EndUpdateSystemGlobalParameter(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginResultTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginResultType", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequestBody Body;
        
        public GetLoginResultTypeRequest() {
        }
        
        public GetLoginResultTypeRequest(Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginResultTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userpwd;
        
        public GetLoginResultTypeRequestBody() {
        }
        
        public GetLoginResultTypeRequestBody(string username, string userpwd) {
            this.username = username;
            this.userpwd = userpwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginResultTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginResultTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponseBody Body;
        
        public GetLoginResultTypeResponse() {
        }
        
        public GetLoginResultTypeResponse(Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginResultTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetLoginResultTypeResult;
        
        public GetLoginResultTypeResponseBody() {
        }
        
        public GetLoginResultTypeResponseBody(int GetLoginResultTypeResult) {
            this.GetLoginResultTypeResult = GetLoginResultTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetWeatherRequestBody Body;
        
        public GetWeatherRequest() {
        }
        
        public GetWeatherRequest(Scada.Client.SL.SystemManagerService.GetWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeatherRequestBody {
        
        public GetWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetWeatherResponseBody Body;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(Scada.Client.SL.SystemManagerService.GetWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeatherResult;
        
        public GetWeatherResponseBody() {
        }
        
        public GetWeatherResponseBody(string GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemParameterManageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemParameterManage", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequestBody Body;
        
        public GetSystemParameterManageRequest() {
        }
        
        public GetSystemParameterManageRequest(Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSystemParameterManageRequestBody {
        
        public GetSystemParameterManageRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemParameterManageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemParameterManageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponseBody Body;
        
        public GetSystemParameterManageResponse() {
        }
        
        public GetSystemParameterManageResponse(Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemParameterManageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSystemParameterManageResult;
        
        public GetSystemParameterManageResponseBody() {
        }
        
        public GetSystemParameterManageResponseBody(string GetSystemParameterManageResult) {
            this.GetSystemParameterManageResult = GetSystemParameterManageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemGlobalParameterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemGlobalParameter", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequestBody Body;
        
        public GetSystemGlobalParameterRequest() {
        }
        
        public GetSystemGlobalParameterRequest(Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSystemGlobalParameterRequestBody {
        
        public GetSystemGlobalParameterRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemGlobalParameterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemGlobalParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponseBody Body;
        
        public GetSystemGlobalParameterResponse() {
        }
        
        public GetSystemGlobalParameterResponse(Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemGlobalParameterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSystemGlobalParameterResult;
        
        public GetSystemGlobalParameterResponseBody() {
        }
        
        public GetSystemGlobalParameterResponseBody(string GetSystemGlobalParameterResult) {
            this.GetSystemGlobalParameterResult = GetSystemGlobalParameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSystemParameterManageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSystemParameterManage", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequestBody Body;
        
        public UpdateSystemParameterManageRequest() {
        }
        
        public UpdateSystemParameterManageRequest(Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSystemParameterManageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemParameterManage;
        
        public UpdateSystemParameterManageRequestBody() {
        }
        
        public UpdateSystemParameterManageRequestBody(string systemParameterManage) {
            this.systemParameterManage = systemParameterManage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSystemParameterManageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSystemParameterManageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponseBody Body;
        
        public UpdateSystemParameterManageResponse() {
        }
        
        public UpdateSystemParameterManageResponse(Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSystemParameterManageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateSystemParameterManageResult;
        
        public UpdateSystemParameterManageResponseBody() {
        }
        
        public UpdateSystemParameterManageResponseBody(bool UpdateSystemParameterManageResult) {
            this.UpdateSystemParameterManageResult = UpdateSystemParameterManageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSystemGlobalParameterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSystemGlobalParameter", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequestBody Body;
        
        public UpdateSystemGlobalParameterRequest() {
        }
        
        public UpdateSystemGlobalParameterRequest(Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSystemGlobalParameterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemGlobalParameter;
        
        public UpdateSystemGlobalParameterRequestBody() {
        }
        
        public UpdateSystemGlobalParameterRequestBody(string systemGlobalParameter) {
            this.systemGlobalParameter = systemGlobalParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSystemGlobalParameterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSystemGlobalParameterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponseBody Body;
        
        public UpdateSystemGlobalParameterResponse() {
        }
        
        public UpdateSystemGlobalParameterResponse(Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSystemGlobalParameterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateSystemGlobalParameterResult;
        
        public UpdateSystemGlobalParameterResponseBody() {
        }
        
        public UpdateSystemGlobalParameterResponseBody(bool UpdateSystemGlobalParameterResult) {
            this.UpdateSystemGlobalParameterResult = UpdateSystemGlobalParameterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemManagerServiceSoapChannel : Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddDDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddDDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoginResultTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoginResultTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSystemParameterManageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSystemParameterManageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSystemGlobalParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSystemGlobalParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateSystemParameterManageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateSystemParameterManageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateSystemGlobalParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateSystemGlobalParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemManagerServiceSoapClient : System.ServiceModel.ClientBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap>, Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap {
        
        private BeginOperationDelegate onBeginAddDDDelegate;
        
        private EndOperationDelegate onEndAddDDDelegate;
        
        private System.Threading.SendOrPostCallback onAddDDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLoginResultTypeDelegate;
        
        private EndOperationDelegate onEndGetLoginResultTypeDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoginResultTypeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWeatherDelegate;
        
        private EndOperationDelegate onEndGetWeatherDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatherCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSystemParameterManageDelegate;
        
        private EndOperationDelegate onEndGetSystemParameterManageDelegate;
        
        private System.Threading.SendOrPostCallback onGetSystemParameterManageCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSystemGlobalParameterDelegate;
        
        private EndOperationDelegate onEndGetSystemGlobalParameterDelegate;
        
        private System.Threading.SendOrPostCallback onGetSystemGlobalParameterCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateSystemParameterManageDelegate;
        
        private EndOperationDelegate onEndUpdateSystemParameterManageDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateSystemParameterManageCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateSystemGlobalParameterDelegate;
        
        private EndOperationDelegate onEndUpdateSystemGlobalParameterDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateSystemGlobalParameterCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SystemManagerServiceSoapClient() {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AddDDCompletedEventArgs> AddDDCompleted;
        
        public event System.EventHandler<GetLoginResultTypeCompletedEventArgs> GetLoginResultTypeCompleted;
        
        public event System.EventHandler<GetWeatherCompletedEventArgs> GetWeatherCompleted;
        
        public event System.EventHandler<GetSystemParameterManageCompletedEventArgs> GetSystemParameterManageCompleted;
        
        public event System.EventHandler<GetSystemGlobalParameterCompletedEventArgs> GetSystemGlobalParameterCompleted;
        
        public event System.EventHandler<UpdateSystemParameterManageCompletedEventArgs> UpdateSystemParameterManageCompleted;
        
        public event System.EventHandler<UpdateSystemGlobalParameterCompletedEventArgs> UpdateSystemGlobalParameterCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddDD(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndAddDD(System.IAsyncResult result) {
            return base.Channel.EndAddDD(result);
        }
        
        private System.IAsyncResult OnBeginAddDD(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginAddDD(x, y, callback, asyncState);
        }
        
        private object[] OnEndAddDD(System.IAsyncResult result) {
            int retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndAddDD(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddDDCompleted(object state) {
            if ((this.AddDDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddDDCompleted(this, new AddDDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddDDAsync(int x, int y) {
            this.AddDDAsync(x, y, null);
        }
        
        public void AddDDAsync(int x, int y, object userState) {
            if ((this.onBeginAddDDDelegate == null)) {
                this.onBeginAddDDDelegate = new BeginOperationDelegate(this.OnBeginAddDD);
            }
            if ((this.onEndAddDDDelegate == null)) {
                this.onEndAddDDDelegate = new EndOperationDelegate(this.OnEndAddDD);
            }
            if ((this.onAddDDCompletedDelegate == null)) {
                this.onAddDDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddDDCompleted);
            }
            base.InvokeAsync(this.onBeginAddDDDelegate, new object[] {
                        x,
                        y}, this.onEndAddDDDelegate, this.onAddDDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginGetLoginResultType(Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoginResultType(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLoginResultType(string username, string userpwd, System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequest inValue = new Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequestBody();
            inValue.Body.username = username;
            inValue.Body.userpwd = userpwd;
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginGetLoginResultType(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndGetLoginResultType(System.IAsyncResult result) {
            return base.Channel.EndGetLoginResultType(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int EndGetLoginResultType(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndGetLoginResultType(result);
            return retVal.Body.GetLoginResultTypeResult;
        }
        
        private System.IAsyncResult OnBeginGetLoginResultType(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string userpwd = ((string)(inValues[1]));
            return this.BeginGetLoginResultType(username, userpwd, callback, asyncState);
        }
        
        private object[] OnEndGetLoginResultType(System.IAsyncResult result) {
            int retVal = this.EndGetLoginResultType(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoginResultTypeCompleted(object state) {
            if ((this.GetLoginResultTypeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoginResultTypeCompleted(this, new GetLoginResultTypeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoginResultTypeAsync(string username, string userpwd) {
            this.GetLoginResultTypeAsync(username, userpwd, null);
        }
        
        public void GetLoginResultTypeAsync(string username, string userpwd, object userState) {
            if ((this.onBeginGetLoginResultTypeDelegate == null)) {
                this.onBeginGetLoginResultTypeDelegate = new BeginOperationDelegate(this.OnBeginGetLoginResultType);
            }
            if ((this.onEndGetLoginResultTypeDelegate == null)) {
                this.onEndGetLoginResultTypeDelegate = new EndOperationDelegate(this.OnEndGetLoginResultType);
            }
            if ((this.onGetLoginResultTypeCompletedDelegate == null)) {
                this.onGetLoginResultTypeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoginResultTypeCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoginResultTypeDelegate, new object[] {
                        username,
                        userpwd}, this.onEndGetLoginResultTypeDelegate, this.onGetLoginResultTypeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginGetWeather(Scada.Client.SL.SystemManagerService.GetWeatherRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeather(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWeather(System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.GetWeatherRequest inValue = new Scada.Client.SL.SystemManagerService.GetWeatherRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.GetWeatherRequestBody();
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginGetWeather(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.GetWeatherResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndGetWeather(System.IAsyncResult result) {
            return base.Channel.EndGetWeather(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetWeather(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.GetWeatherResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndGetWeather(result);
            return retVal.Body.GetWeatherResult;
        }
        
        private System.IAsyncResult OnBeginGetWeather(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetWeather(callback, asyncState);
        }
        
        private object[] OnEndGetWeather(System.IAsyncResult result) {
            string retVal = this.EndGetWeather(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatherCompleted(object state) {
            if ((this.GetWeatherCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatherCompleted(this, new GetWeatherCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatherAsync() {
            this.GetWeatherAsync(null);
        }
        
        public void GetWeatherAsync(object userState) {
            if ((this.onBeginGetWeatherDelegate == null)) {
                this.onBeginGetWeatherDelegate = new BeginOperationDelegate(this.OnBeginGetWeather);
            }
            if ((this.onEndGetWeatherDelegate == null)) {
                this.onEndGetWeatherDelegate = new EndOperationDelegate(this.OnEndGetWeather);
            }
            if ((this.onGetWeatherCompletedDelegate == null)) {
                this.onGetWeatherCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatherCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatherDelegate, null, this.onEndGetWeatherDelegate, this.onGetWeatherCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginGetSystemParameterManage(Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSystemParameterManage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSystemParameterManage(System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequest inValue = new Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequestBody();
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginGetSystemParameterManage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndGetSystemParameterManage(System.IAsyncResult result) {
            return base.Channel.EndGetSystemParameterManage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetSystemParameterManage(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndGetSystemParameterManage(result);
            return retVal.Body.GetSystemParameterManageResult;
        }
        
        private System.IAsyncResult OnBeginGetSystemParameterManage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSystemParameterManage(callback, asyncState);
        }
        
        private object[] OnEndGetSystemParameterManage(System.IAsyncResult result) {
            string retVal = this.EndGetSystemParameterManage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSystemParameterManageCompleted(object state) {
            if ((this.GetSystemParameterManageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSystemParameterManageCompleted(this, new GetSystemParameterManageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSystemParameterManageAsync() {
            this.GetSystemParameterManageAsync(null);
        }
        
        public void GetSystemParameterManageAsync(object userState) {
            if ((this.onBeginGetSystemParameterManageDelegate == null)) {
                this.onBeginGetSystemParameterManageDelegate = new BeginOperationDelegate(this.OnBeginGetSystemParameterManage);
            }
            if ((this.onEndGetSystemParameterManageDelegate == null)) {
                this.onEndGetSystemParameterManageDelegate = new EndOperationDelegate(this.OnEndGetSystemParameterManage);
            }
            if ((this.onGetSystemParameterManageCompletedDelegate == null)) {
                this.onGetSystemParameterManageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSystemParameterManageCompleted);
            }
            base.InvokeAsync(this.onBeginGetSystemParameterManageDelegate, null, this.onEndGetSystemParameterManageDelegate, this.onGetSystemParameterManageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginGetSystemGlobalParameter(Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSystemGlobalParameter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSystemGlobalParameter(System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequest inValue = new Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequestBody();
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginGetSystemGlobalParameter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndGetSystemGlobalParameter(System.IAsyncResult result) {
            return base.Channel.EndGetSystemGlobalParameter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetSystemGlobalParameter(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndGetSystemGlobalParameter(result);
            return retVal.Body.GetSystemGlobalParameterResult;
        }
        
        private System.IAsyncResult OnBeginGetSystemGlobalParameter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSystemGlobalParameter(callback, asyncState);
        }
        
        private object[] OnEndGetSystemGlobalParameter(System.IAsyncResult result) {
            string retVal = this.EndGetSystemGlobalParameter(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSystemGlobalParameterCompleted(object state) {
            if ((this.GetSystemGlobalParameterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSystemGlobalParameterCompleted(this, new GetSystemGlobalParameterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSystemGlobalParameterAsync() {
            this.GetSystemGlobalParameterAsync(null);
        }
        
        public void GetSystemGlobalParameterAsync(object userState) {
            if ((this.onBeginGetSystemGlobalParameterDelegate == null)) {
                this.onBeginGetSystemGlobalParameterDelegate = new BeginOperationDelegate(this.OnBeginGetSystemGlobalParameter);
            }
            if ((this.onEndGetSystemGlobalParameterDelegate == null)) {
                this.onEndGetSystemGlobalParameterDelegate = new EndOperationDelegate(this.OnEndGetSystemGlobalParameter);
            }
            if ((this.onGetSystemGlobalParameterCompletedDelegate == null)) {
                this.onGetSystemGlobalParameterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSystemGlobalParameterCompleted);
            }
            base.InvokeAsync(this.onBeginGetSystemGlobalParameterDelegate, null, this.onEndGetSystemGlobalParameterDelegate, this.onGetSystemGlobalParameterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginUpdateSystemParameterManage(Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateSystemParameterManage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateSystemParameterManage(string systemParameterManage, System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequest inValue = new Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequestBody();
            inValue.Body.systemParameterManage = systemParameterManage;
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginUpdateSystemParameterManage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndUpdateSystemParameterManage(System.IAsyncResult result) {
            return base.Channel.EndUpdateSystemParameterManage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndUpdateSystemParameterManage(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndUpdateSystemParameterManage(result);
            return retVal.Body.UpdateSystemParameterManageResult;
        }
        
        private System.IAsyncResult OnBeginUpdateSystemParameterManage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string systemParameterManage = ((string)(inValues[0]));
            return this.BeginUpdateSystemParameterManage(systemParameterManage, callback, asyncState);
        }
        
        private object[] OnEndUpdateSystemParameterManage(System.IAsyncResult result) {
            bool retVal = this.EndUpdateSystemParameterManage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateSystemParameterManageCompleted(object state) {
            if ((this.UpdateSystemParameterManageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateSystemParameterManageCompleted(this, new UpdateSystemParameterManageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateSystemParameterManageAsync(string systemParameterManage) {
            this.UpdateSystemParameterManageAsync(systemParameterManage, null);
        }
        
        public void UpdateSystemParameterManageAsync(string systemParameterManage, object userState) {
            if ((this.onBeginUpdateSystemParameterManageDelegate == null)) {
                this.onBeginUpdateSystemParameterManageDelegate = new BeginOperationDelegate(this.OnBeginUpdateSystemParameterManage);
            }
            if ((this.onEndUpdateSystemParameterManageDelegate == null)) {
                this.onEndUpdateSystemParameterManageDelegate = new EndOperationDelegate(this.OnEndUpdateSystemParameterManage);
            }
            if ((this.onUpdateSystemParameterManageCompletedDelegate == null)) {
                this.onUpdateSystemParameterManageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateSystemParameterManageCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateSystemParameterManageDelegate, new object[] {
                        systemParameterManage}, this.onEndUpdateSystemParameterManageDelegate, this.onUpdateSystemParameterManageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.BeginUpdateSystemGlobalParameter(Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateSystemGlobalParameter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateSystemGlobalParameter(string systemGlobalParameter, System.AsyncCallback callback, object asyncState) {
            Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequest inValue = new Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequest();
            inValue.Body = new Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequestBody();
            inValue.Body.systemGlobalParameter = systemGlobalParameter;
            return ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).BeginUpdateSystemGlobalParameter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap.EndUpdateSystemGlobalParameter(System.IAsyncResult result) {
            return base.Channel.EndUpdateSystemGlobalParameter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndUpdateSystemGlobalParameter(System.IAsyncResult result) {
            Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse retVal = ((Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap)(this)).EndUpdateSystemGlobalParameter(result);
            return retVal.Body.UpdateSystemGlobalParameterResult;
        }
        
        private System.IAsyncResult OnBeginUpdateSystemGlobalParameter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string systemGlobalParameter = ((string)(inValues[0]));
            return this.BeginUpdateSystemGlobalParameter(systemGlobalParameter, callback, asyncState);
        }
        
        private object[] OnEndUpdateSystemGlobalParameter(System.IAsyncResult result) {
            bool retVal = this.EndUpdateSystemGlobalParameter(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateSystemGlobalParameterCompleted(object state) {
            if ((this.UpdateSystemGlobalParameterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateSystemGlobalParameterCompleted(this, new UpdateSystemGlobalParameterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateSystemGlobalParameterAsync(string systemGlobalParameter) {
            this.UpdateSystemGlobalParameterAsync(systemGlobalParameter, null);
        }
        
        public void UpdateSystemGlobalParameterAsync(string systemGlobalParameter, object userState) {
            if ((this.onBeginUpdateSystemGlobalParameterDelegate == null)) {
                this.onBeginUpdateSystemGlobalParameterDelegate = new BeginOperationDelegate(this.OnBeginUpdateSystemGlobalParameter);
            }
            if ((this.onEndUpdateSystemGlobalParameterDelegate == null)) {
                this.onEndUpdateSystemGlobalParameterDelegate = new EndOperationDelegate(this.OnEndUpdateSystemGlobalParameter);
            }
            if ((this.onUpdateSystemGlobalParameterCompletedDelegate == null)) {
                this.onUpdateSystemGlobalParameterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateSystemGlobalParameterCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateSystemGlobalParameterDelegate, new object[] {
                        systemGlobalParameter}, this.onEndUpdateSystemGlobalParameterDelegate, this.onUpdateSystemGlobalParameterCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap CreateChannel() {
            return new SystemManagerServiceSoapClientChannel(this);
        }
        
        private class SystemManagerServiceSoapClientChannel : ChannelBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap>, Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap {
            
            public SystemManagerServiceSoapClientChannel(System.ServiceModel.ClientBase<Scada.Client.SL.SystemManagerService.SystemManagerServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddDD(int x, int y, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = x;
                _args[1] = y;
                System.IAsyncResult _result = base.BeginInvoke("AddDD", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddDD(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddDD", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLoginResultType(Scada.Client.SL.SystemManagerService.GetLoginResultTypeRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLoginResultType", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse EndGetLoginResultType(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse _result = ((Scada.Client.SL.SystemManagerService.GetLoginResultTypeResponse)(base.EndInvoke("GetLoginResultType", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWeather(Scada.Client.SL.SystemManagerService.GetWeatherRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWeather", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.GetWeatherResponse EndGetWeather(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.GetWeatherResponse _result = ((Scada.Client.SL.SystemManagerService.GetWeatherResponse)(base.EndInvoke("GetWeather", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSystemParameterManage(Scada.Client.SL.SystemManagerService.GetSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSystemParameterManage", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse EndGetSystemParameterManage(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse _result = ((Scada.Client.SL.SystemManagerService.GetSystemParameterManageResponse)(base.EndInvoke("GetSystemParameterManage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSystemGlobalParameter(Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSystemGlobalParameter", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse EndGetSystemGlobalParameter(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse _result = ((Scada.Client.SL.SystemManagerService.GetSystemGlobalParameterResponse)(base.EndInvoke("GetSystemGlobalParameter", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateSystemParameterManage(Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateSystemParameterManage", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse EndUpdateSystemParameterManage(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse _result = ((Scada.Client.SL.SystemManagerService.UpdateSystemParameterManageResponse)(base.EndInvoke("UpdateSystemParameterManage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateSystemGlobalParameter(Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateSystemGlobalParameter", _args, callback, asyncState);
                return _result;
            }
            
            public Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse EndUpdateSystemGlobalParameter(System.IAsyncResult result) {
                object[] _args = new object[0];
                Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse _result = ((Scada.Client.SL.SystemManagerService.UpdateSystemGlobalParameterResponse)(base.EndInvoke("UpdateSystemGlobalParameter", _args, result)));
                return _result;
            }
        }
    }
}
